camera:
  resolution:
    width: 1280
    height: 1024
  fps: 30
  api_preference: CAP_DSHOW
  buffer_size: 10
  log_interval: 2

logging:
  level: INFO
  max_files: 5
  file_size_mb: 10
  format: "%(asctime)s - %(levelname)s - %(message)s"